
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: uhi_postgres_5434
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uhi_db
    ports:
      - "5434:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./initdb/data:/docker-entrypoint-initdb.d/data
    networks:
      - uhi_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: uhi_pgadmin_8082
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@uhi.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - postgres
    networks:
      - uhi_net

networks:
  uhi_net:
    driver: bridge
